site_name: Envi Developer Resources
nav:
  - API Topics:
    - Introduction: index.md
    - Testing with Postman: Testing with Postman.md 
    - Retrieving Data Using cURL: Retrieving_Data.md
    - Options and Limitations: Options_and_Limitations.md
    - Custom Options: Custom_Options.md
    - Metadata: Metadata.md
    - Metadata Controlling: Metadata_Controlling.md
    - Rate Limiting: Rate_Limiting.md
    - API Versioning: API_Versioning.md
    - Envi OData Examples: Envi_OData_Examples.md
    - Envi Use Cases: Envi_Use_Cases.md
    - Bi Tool Use Cases: BI_Tool_Use_Cases.md
    - Integrators: Integrators.md
    - GitHub Repository: GitHub_Repository.md
  - API Operations:
    - Authentication: Authentication_POST.md
    - Addresses: Addresses.md
    - AdjustmentItems: AdjustmentItems.md
    - AP Batch: AP_Batch.md
    - Classifications: Classifications.md
    - Departments: Departments.md
    - Facilities: Facilities.md
    - FileAttachments: FileAttachments.md
    - FuturePricing: FuturePricing.md
    - Inventory: Inventory.md
    - InventoryActivity: InventoryActivity.md
    - InventoryLocations: InventoryLocations.md
    - InventoryLocationsCostAnd <br> Quantity: InventoryLocationsCostAndQuantity.md
    - InventoryLocationsExtended: InventoryLocationsExtended.md
    - InventorySnapshotItems: InventorySnapshotItems.md
    - InventorySnapshots: InventorySnapshots.md
    - InventoryTrackings: InventoryTrackings.md
    - InventoryUOMs: InventoryUOMs.md
    - InventoryVendors: InventoryVendors.md
    - Locations: Locations.md
    - Manufacturers: Manufacturers.md
    - MatchedInvoiceItems: MatchedInvoiceItems.md
    - MatchedInvoices: MatchedInvoices.md
    - PARAreaItems: PARAreaItems.md
    - PARAreas: PARAreas.md
    - POConfirmationItems: POConfirmationItems.md
    - POConfirmations: POConfirmations.md
    - PurchaseOrderItems: PurchaseOrderItems.md
    - PurchaseOrders: PurchaseOrders.md
    - PurchasingUnits: PurchasingUnits.md 
    - ReceiptItems: ReceiptItems.md
    - Receipts: Receipts.md
    - RequisitionFillItems: RequisitionFillItems.md
    - RequisitionFills: RequisitionFills.md
    - RequisitionItems: RequisitionItems.md
    - Requisitions: Requisitions.md
    - UsageItems: UsageItems.md
    - UsageProcedures: UsageProcedures.md
    - Usages: Usages.md
    - VendorAddresses: VendorAddresses.md
    - VendorContacts: VendorContacts.md
    - VendorEmailConfigurations: VendorEmailConfigurations.md
    - VendorFacilities: VendorFacilities.md
    - VendorFaxConfigurations: VendorFaxConfigurations.md
    - Vendors: Vendors.md
  - Integrations:
    - SSO Integrations: SSO_Integrations.md
    - IP Addresses and Domains: IP_Addresses_and_Domains.md


theme:
  name: material
  font:
    text: Segoe UI
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: black
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: black
      accent: indigo
  logo: assets/logo.png
  favicon: img/favicon.png
  features:
    - navigation.tabs
    - navigation.top

use_directory_urls: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


extra_css:
  - stylesheets/extra.css

